- name: Apache, установка и конфигурирование
  hosts: centos
  vars_files:
    - ../../vars/vars.yaml
  become: true
  gather_facts: true

  tasks:
    - name: Установка Apache
      yum:
        name: httpd
        state: present

    - name: Включение и запуск Apache
      systemd_service:
        name: httpd
        enabled: yes
        state: started

    - name: Создание директории для расширений
      file:
        path: /etc/systemd/system/httpd.service.d
        state: directory

    - name: Создание расширения
      file:
        path: /etc/systemd/system/httpd.service.d/httpd.conf
        state: touch

    - name: Добавление переменной окружения APACHE_LOG_DIR
      blockinfile:
        path: /etc/systemd/system/httpd.service.d/httpd.conf
        block: |
          [Service]
          Environment=APACHE_LOG_DIR=/var/log/httpd

    - name: Создание файла конфигурации портов
      file:
        path: /etc/httpd/conf/ports.conf
        state: touch

    - name: Добавление листнера на порт 8080 в файл конфигурации портов
      lineinfile:
        path: /etc/httpd/conf/ports.conf
        line: 'Listen 8080'

    - name: Подключение файла конфигурации портов
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        insertafter: 'Include conf.modules.d/*.conf'
        line: 'Include conf/ports.conf'

    - name: Вывод листнера с 80 порта
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        search_string: 'Listen 80'
        line: '#Listen 80'

    - name: Копирование конфигурационного файла Apache
      template:
        src: ../../templates/apache.conf.j2
        dest: /etc/httpd/conf.d/vhost.conf
      notify: Перезапуск Apache

  handlers:
    - name: Перезапуск Apache
      systemd_service:
        daemon_reload: true
        name: httpd
        state: restarted